import { MAX_COLOURS, TYPES, PRESETS, POPULAR, FONTS, FRAME_OPTIONS, INITIAL_TIME, typeById, defaultParams, initialState, applyPreset, equalDivisions, controlPoints, createText, colourName, contrastRatio, clamp, uid, encodeDesign, decodeDesign, normalizeState, type StudioState, type TextLayer, type ImageLayer } from './model';
import { paintGradient, renderComposition, loadImage } from './renderer';
import { DesignStore, loadDraft, loadSaved, DRAFT_KEY, SAVED_KEY, type SavedDesign } from './store';
import { inspectorHTML, paletteHTML, paletteGridHTML, savedHTML, icon, titleCase, type InspectorOptions } from './ui';
import { escapeHtml as esc } from './export';
import { setupDialogs } from './dialogs';
import { balanceGradient, backdropColours } from './appearance';
import { GLOW_PALETTES } from './glow.ts';
import { LINE_PALETTES } from './lines.ts';
import { FORM_PALETTES } from './forms.ts';

const $=<T extends Element=HTMLElement>(selector:string)=>document.querySelector<T>(selector)!;
let initial=initialState(),saved:SavedDesign[]=[],startupMessage='';
try{initial=loadDraft(localStorage)??initial;saved=loadSaved(localStorage);}catch{startupMessage='Browser storage is unavailable. You can still create and export designs.';}
if(location.hash.startsWith('#g=')){try{initial=decodeDesign(location.hash.slice(3));startupMessage='Shared design opened.';}catch(e){startupMessage=(e as Error).message;}}
const store=new DesignStore(initial);
let clock=initial.time,view='studio',paused=matchMedia('(prefers-reduced-motion: reduce)').matches,lastSpeed=initial.speed||30,showTags=true,showContrast=false,dirty=true,frameWidth=1,frameHeight=1;
let lastDraw=0,lastTick=0,lastContrast=0,draftTimer=0,toastTimer=0,storageWarning=false,animationFrame=0;
let paletteFilter='All',paletteSort='hue',paletteQuery='';
let selectedColour=0,lastBalance='',lastBackdrop='';
let inspector:InspectorOptions={panel:'design',family:POPULAR.includes(initial.type)?'Popular':typeById(initial.type).family,selectedText:initial.texts[0]?.id??null,expandedPresets:false,selectedPreset:PRESETS.findIndex(p=>p.name===initial.name&&p.type===initial.type)};
const canvas=$<HTMLCanvasElement>('#gradient-canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true})!,stage=$('#canvas-stage'),frame=$('#canvas-frame'),inspectorContent=$('#inspector-content');
const snapshot=():StudioState=>({...structuredClone(store.state),time:clock});
const dialogs=setupDialogs({state:snapshot,update:(change,group)=>{inspector.selectedPreset=-1;store.update(change,group);},refresh:refreshAll,toast,copy:copyText,save:saveDesign,aspect:()=>frameWidth/frameHeight});
function toast(message:string,undo?:()=>void){clearTimeout(toastTimer);const el=$('#toast');el.textContent=message;el.hidden=false;if(undo){const button=document.createElement('button');button.textContent='Undo';button.addEventListener('click',()=>{undo();el.hidden=true;},{once:true});el.append(button);}toastTimer=window.setTimeout(()=>{el.hidden=true;},undo?7000:4200);}
async function copyText(text:string,message='Copied.'){try{await navigator.clipboard.writeText(text);toast(message);}catch{dialogs.copyFallback(text);}}
function writeSaved(next:SavedDesign[]){localStorage.setItem(SAVED_KEY,JSON.stringify(next));saved=next;renderCounts();if(view==='saved')renderSaved();}
function saveDraft(){clearTimeout(draftTimer);draftTimer=window.setTimeout(()=>{try{localStorage.setItem(DRAFT_KEY,JSON.stringify(snapshot()));}catch{if(!storageWarning){storageWarning=true;toast('The browser could not save your draft. Export a JSON design to keep a copy.');}}},650);}
function renderCounts(){const count=$('#saved-count');count.textContent=String(saved.length);count.hidden=saved.length===0;}
function selectedText(){return store.state.texts.find(t=>t.id===inspector.selectedText)??store.state.texts[0];}
function refreshAll(){renderInspector();updateLayers();updateBalance();updateBackdrop();resizeCanvas();updateStatus();if(view==='saved')renderSaved();dirty=true;}
function renderInspector(){const scroll=inspectorContent.scrollTop;inspectorContent.innerHTML=inspectorHTML(store.state,inspector);inspectorContent.scrollTop=scroll;document.querySelectorAll<HTMLButtonElement>('[data-panel]').forEach(b=>{b.classList.toggle('active',b.dataset.panel===inspector.panel);b.setAttribute('aria-selected',String(b.dataset.panel===inspector.panel));b.tabIndex=b.dataset.panel===inspector.panel?0:-1;});
 const thumbnails=Array.from(inspectorContent.querySelectorAll<HTMLCanvasElement>('[data-type-thumb]'));requestAnimationFrame(()=>{for(const c of thumbnails){if(!c.isConnected)continue;const type=c.dataset.typeThumb!,p=PRESETS.find(p=>p.type===type),base=p?applyPreset(initialState(),p):{...initialState(),type,params:defaultParams(type)};paintGradient(c.getContext('2d')!,c.width,c.height,{...base,grain:0,soften:0},INITIAL_TIME,'thumbnail');}});
 const presets=Array.from(inspectorContent.querySelectorAll<HTMLCanvasElement>('[data-preset-thumb]'));requestAnimationFrame(()=>{for(const c of presets){if(!c.isConnected)continue;const preset=PRESETS[Number(c.dataset.presetThumb)];if(!preset)continue;const base=applyPreset(initialState(),preset);paintGradient(c.getContext('2d')!,c.width,c.height,{...base,grain:0,soften:0},INITIAL_TIME,'thumbnail');}});
}
function updateStatus(){const s=store.state,kind=typeById(s.type);$('#blend-name').textContent=s.name;$('#blend-type').textContent=kind.name.toUpperCase();$<HTMLButtonElement>('#undo').disabled=!store.canUndo;$<HTMLButtonElement>('#redo').disabled=!store.canRedo;
 const moving=!!kind.animated&&s.speed>0&&!paused;$('#play-pause').innerHTML=icon(moving?'pause':'play',17);$('#play-pause').setAttribute('aria-label',moving?'Pause animation':'Play animation');$('#play-pause').setAttribute('aria-pressed',String(moving));$<HTMLButtonElement>('#play-pause').disabled=!kind.animated;$('#playback-label').textContent=kind.animated?(moving?'In motion':'Paused'):'Still frame';$('.live-dot').classList.toggle('paused',!moving);
}
function resizeCanvas(){if(view!=='studio')return;const bounds=stage.getBoundingClientRect();if(bounds.width<2||bounds.height<2)return;const ratio=FRAME_OPTIONS.find(f=>f.id===store.state.frame)?.ratio??0;let w=bounds.width,h=bounds.height;if(ratio){w=Math.min(bounds.width,bounds.height*ratio);h=w/ratio;}frame.style.width=`${w}px`;frame.style.height=`${h}px`;frame.classList.toggle('framed',!!ratio);frameWidth=w;frameHeight=h;const pixelRatio=Math.min(window.devicePixelRatio||1,1.5),resolution=Math.min(1400/w,pixelRatio),cw=Math.round(w*resolution),ch=Math.round(h*resolution);if(canvas.width!==cw||canvas.height!==ch){canvas.width=cw;canvas.height=ch;dirty=true;}updateTextLayers();updateImageLayer();}
function updateTextLayers(){const layer=$('#text-layer'),s=store.state;layer.innerHTML=s.texts.map(t=>{const selected=inspector.panel==='text'&&selectedText()?.id===t.id,f=FONTS.find(f=>f.id===t.font)??FONTS[0],fontSize=frameWidth*t.size/100;return `<span class="canvas-text ${selected?'selected':''}" role="button" tabindex="0" data-drag-text="${t.id}" aria-label="Move text: ${esc(t.content.slice(0,60))}" style="left:${t.x}%;top:${t.y}%;font-family:${esc(f.family)};font-size:${fontSize}px;font-weight:${t.weight};color:${t.color};text-align:${t.align};opacity:${t.opacity/100};letter-spacing:${t.tracking/100}em;transform:translate(-50%,-50%) rotate(${t.rotation}deg);text-shadow:${t.shadow?`0 ${fontSize*.04}px ${fontSize*.18}px rgba(0,0,0,${t.shadow/120})`:'none'}">${esc(t.content)}</span>`;}).join('');}
function updateImageLayer(){const i=store.state.image,layer=$('#image-layer');if(!i){layer.innerHTML='';return;}let image=layer.querySelector<HTMLImageElement>('img');if(!image){image=new Image();image.alt='Your image layer';image.draggable=false;image.dataset.dragImage='true';image.tabIndex=0;image.setAttribute('role','button');image.setAttribute('aria-label','Move image');layer.append(image);}if(image.getAttribute('src')!==i.src)image.src=i.src;layer.style.mixBlendMode=i.blend;image.style.cssText=`left:${i.x}%;top:${i.y}%;width:${i.width}%;transform:translate(-50%,-50%) rotate(${i.rotation}deg);opacity:${i.opacity/100};border-radius:${Math.min(frameWidth*i.width/100,frameWidth*i.width/100/i.aspect)*i.radius/100}px;filter:brightness(${i.brightness}%) contrast(${i.contrast}%) blur(${i.blur*frameWidth/1000}px)`;image.classList.toggle('selected',inspector.panel==='image');}
function updatePoints(){const s=store.state,layer=$('#point-layer'),visible=showTags&&['flow','mesh'].includes(s.type)&&inspector.panel==='design';layer.hidden=!visible;if(!visible)return;const points=controlPoints(s);layer.innerHTML=points.map((p,i)=>`<button class="colour-point" data-point="${i}" aria-label="Move colour ${i+1}: ${esc(colourName(s.colors[i]))}" style="left:${clamp(p[0]*100,2,98)}%;top:${clamp(p[1]*100,3,97)}%;--point-colour:${s.colors[i]}"><span></span></button>`).join('');}
function updateTags(){const s=store.state,layer=$('#color-tags');layer.hidden=!showTags;layer.innerHTML=s.colors.map((c,i)=>`<button class="colour-tag" data-colour="${i}" style="top:${13+i/(s.colors.length-1)*65}%"><i style="background:${c}"></i><span>${titleCase(colourName(c))}</span><small>${c}</small></button>`).join('');}
function updateLayers(){updateTextLayers();updateImageLayer();updatePoints();updateTags();}
function updateBalance(){
 const track=$('#balance-track'),s=store.state,bounds=[0,...s.divisions,1];
 selectedColour=Math.min(selectedColour,s.colors.length-1);
 $('.balance-wrap p').textContent=['bars','columns'].includes(s.type)
  ?'Drag the handles to set each colour’s height along the bars. Tap a band to edit it.'
  :['glow','lines','forms'].includes(s.type)
   ?'The first colour is the background. The remaining colours light the shapes.'
  :['flow','mesh'].includes(s.type)
   ?'Bands set how far each colour reaches. Rings on the canvas place it.'
   :'Drag the handles to balance the gradient. Tap a band to edit its colour.';
 const signature=JSON.stringify([s.colors,s.divisions,selectedColour]);
 if(signature===lastBalance)return;lastBalance=signature;
 track.style.background=balanceGradient(s.colors,s.divisions);
 const bands=s.colors.map((color,i)=>`<button class="balance-band ${i===selectedColour?'selected':''}" data-colour="${i}" style="left:${bounds[i]*100}%;width:${(bounds[i+1]-bounds[i])*100}%" aria-label="Edit colour ${i+1}: ${esc(colourName(color))}" aria-pressed="${i===selectedColour}"></button>`).join('');
 const handles=s.divisions.map((v,i)=>`<button class="balance-handle" role="slider" data-balance="${i}" style="left:${v*100}%" aria-label="Balance between colour ${i+1} and ${i+2}" aria-valuemin="${Math.round((s.divisions[i-1]??0)*100+1)}" aria-valuemax="${Math.round((s.divisions[i+1]??1)*100-1)}" aria-valuenow="${Math.round(v*100)}"></button>`).join('');
 track.innerHTML=bands+handles;
}
function updateBackdrop(){
 const s=store.state,signature=JSON.stringify([s.colors,s.divisions]);
 if(signature===lastBackdrop)return;lastBackdrop=signature;
 backdropColours(s.colors,s.divisions).forEach((color,i)=>document.documentElement.style.setProperty(`--backdrop-${i+1}`,color));
}
function setView(next:string){if(!['studio','palette','saved'].includes(next))return;view=next;for(const v of ['studio','palette','saved'])$('#'+v+'-view').hidden=v!==view;document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>{const active=b.dataset.view===view;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});if(view==='palette'){if(!$('#palette-view').children.length)$('#palette-view').innerHTML=paletteHTML();renderPalette();}if(view==='saved')renderSaved();if(view==='studio')requestAnimationFrame(()=>{resizeCanvas();dirty=true;});}
function setPanel(panel:string){inspector.panel=panel;inspectorContent.scrollTop=0;renderInspector();updateLayers();}
function renderPalette(){$('#palette-grid').innerHTML=paletteGridHTML(paletteQuery,paletteFilter,paletteSort);}
function renderSaved(){$('#saved-view').innerHTML=savedHTML(saved);}
function changeType(id:string){if(!TYPES.some(t=>t.id===id))return;const p=PRESETS.find(p=>p.type===id),next=p?applyPreset(store.state,p):{...store.state,type:id,params:defaultParams(id),speed:typeById(id).animated?30:0};store.update(next);clock=INITIAL_TIME;inspector.selectedPreset=p?PRESETS.indexOf(p):-1;inspector.expandedPresets=false;refreshAll();}
function changePreset(index:number){const preset=PRESETS[index];if(!preset)return;const next=applyPreset(store.state,preset);if(preset.type==='lines'&&store.state.type==='lines'){next.colors=[...store.state.colors];next.divisions=[...store.state.divisions];}store.update(next);clock=INITIAL_TIME;inspector.selectedPreset=index;refreshAll();}
function addColour(color?:string){const s=store.state;if(s.colors.length>=MAX_COLOURS){toast('A blend can have up to 12 colours. Edit or remove one to make room.');return;}const colors=[...s.colors,color??'#D6BBC6'];store.update({colors,divisions:equalDivisions(colors.length),points:s.points.length?[...s.points,[.25+Math.random()*.5,.25+Math.random()*.5]]:[]});inspector.selectedPreset=-1;refreshAll();if(!color)dialogs.colour(colors.length-1);}
function removeColour(index:number){if(store.state.colors.length<=2)return;store.update(s=>{s.colors.splice(index,1);s.divisions=equalDivisions(s.colors.length);if(s.points.length)s.points.splice(index,1);});inspector.selectedPreset=-1;refreshAll();}
function togglePlayback(){if(!typeById(store.state.type).animated)return;if(paused){paused=false;if(!store.state.speed)store.update({speed:lastSpeed});}else if(store.state.speed>0){lastSpeed=store.state.speed;store.update({speed:0});}else store.update({speed:lastSpeed});updateStatus();renderInspector();dirty=true;}
function randomize(){const candidates=PRESETS.filter(p=>POPULAR.includes(p.type)),p=candidates[Math.floor(Math.random()*candidates.length)];inspector.family='Popular';changePreset(PRESETS.indexOf(p));toast(p.name);}
function undo(){store.undo();clock=store.state.time;refreshAll();}function redo(){store.redo();clock=store.state.time;refreshAll();}
async function share(){const state=snapshot(),link=`${location.origin}/pigment/#g=${encodeDesign(state)}`;await copyText(link,state.image?'Link copied. The uploaded image stays in this browser; export JSON to include it.':'Link copied. Anyone with it can open this design.');}
async function saveDesign(name:string){try{const state={...snapshot(),name},preview=await renderComposition(state,320,Math.round(320/(frameWidth/frameHeight))),thumbnail=preview.toDataURL('image/webp',.75);if(saved.length>=60)throw new Error('Your collection has 60 designs. Export or remove a few before saving more.');writeSaved([{id:uid(),name,date:new Date().toISOString(),state,thumbnail},...saved]);store.update({name});toast('Saved to your collection.');}catch(e){toast((e as Error).name==='QuotaExceededError'?'Browser storage is full. Export this design as JSON to keep a copy.':(e as Error).message);}}
function openSaved(id:string){const item=saved.find(s=>s.id===id);if(!item)return;store.replace(item.state);clock=item.state.time;inspector.selectedText=store.state.texts[0]?.id??null;inspector.family=POPULAR.includes(store.state.type)?'Popular':typeById(store.state.type).family;inspector.selectedPreset=-1;setView('studio');refreshAll();toast('Design opened.');}
function removeSaved(id:string){const index=saved.findIndex(s=>s.id===id),item=saved[index];if(!item)return;try{writeSaved(saved.filter(s=>s.id!==id));toast('Removed from your collection.',()=>{try{const next=[...saved];next.splice(Math.min(index,next.length),0,item);writeSaved(next);}catch{toast('The design could not be restored. Browser storage may be full.');}});}catch{toast('The collection could not be updated.');}}
async function uploadImage(file:File){
 if(!/^image\/(png|jpeg|webp|avif)$/.test(file.type)){toast('Choose a PNG, JPG, WebP, or AVIF image.');return;}if(file.size>20*1024*1024){toast('Choose an image smaller than 20 MB.');return;}
 const url=URL.createObjectURL(file);try{const image=await loadImage(url),factor=Math.min(1,1400/Math.max(image.naturalWidth,image.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(image.naturalWidth*factor));c.height=Math.max(1,Math.round(image.naturalHeight*factor));c.getContext('2d')!.drawImage(image,0,0,c.width,c.height);let src=c.toDataURL('image/webp',.86);if(src.length>2600000)src=c.toDataURL('image/webp',.65);if(src.length>2800000)throw new Error('This image is too detailed to keep in browser storage. Try a smaller image.');const spec:ImageLayer={src,name:file.name,x:50,y:50,width:45,rotation:0,opacity:100,radius:0,blend:'normal',brightness:100,contrast:100,blur:0,aspect:c.width/c.height};store.update({image:spec});setPanel('image');toast('Image added. Drag it on the canvas to place it.');}catch(e){toast((e as Error).message);}finally{URL.revokeObjectURL(url);}
}
async function extractImageColours(){const spec=store.state.image;if(!spec)return;try{const image=await loadImage(spec.src),c=document.createElement('canvas');c.width=64;c.height=64;const context=c.getContext('2d')!;context.drawImage(image,0,0,64,64);const data=context.getImageData(0,0,64,64).data,bins=new Map<string,{sum:number[];count:number}>();for(let p=0;p<data.length;p+=4){if(data[p+3]<128)continue;const key=`${data[p]>>5},${data[p+1]>>5},${data[p+2]>>5}`,bin=bins.get(key)??{sum:[0,0,0],count:0};for(let j=0;j<3;j++)bin.sum[j]+=data[p+j];bin.count++;bins.set(key,bin);}const candidates=[...bins.values()].sort((a,b)=>b.count-a.count).map(b=>b.sum.map(n=>Math.round(n/b.count))),chosen:number[][]=[];for(const color of candidates){if(chosen.every(c=>c.reduce((total,v,i)=>total+Math.abs(v-color[i]),0)>85))chosen.push(color);if(chosen.length===5)break;}if(!chosen.length)throw new Error('No visible colours were found in this image.');if(chosen.length===1)chosen.push([255,255,255]);const colors=chosen.map(c=>'#'+c.map(n=>n.toString(16).padStart(2,'0')).join('').toUpperCase());store.update({colors,points:[],divisions:equalDivisions(colors.length),name:'Colours from '+spec.name.replace(/\.[^.]+$/,'')});inspector.selectedPreset=-1;refreshAll();toast('Image colours added to your gradient.');}catch(e){toast((e as Error).message);}}
async function importDesign(file:File){if(file.size>4*1024*1024){toast('Choose a design file smaller than 4 MB.');return;}try{const state=normalizeState(JSON.parse(await file.text()));store.replace(state);clock=state.time;inspector.family=POPULAR.includes(state.type)?'Popular':typeById(state.type).family;setView('studio');refreshAll();toast('Design imported.');}catch{toast('This file is not a valid Pigment Studio design.');}}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await stage.requestFullscreen();}catch{stage.classList.toggle('fallback-fullscreen');resizeCanvas();}}

store.subscribe(()=>{dirty=true;updateLayers();updateBalance();updateBackdrop();updateStatus();saveDraft();});
const observer=new ResizeObserver(resizeCanvas);observer.observe(stage);document.fonts.ready.then(()=>{dirty=true;updateTextLayers();});
function animate(now:number){animationFrame=requestAnimationFrame(animate);if(view!=='studio'||document.hidden){lastTick=now;return;}const elapsed=lastTick?Math.min(.05,(now-lastTick)/1000):0;lastTick=now;const s=store.state,moving=typeById(s.type).animated&&s.speed>0&&!paused;if(moving){clock+=elapsed*s.speed/100*1.2;dirty=true;}if(dirty&&now-lastDraw>=32){paintGradient(ctx,canvas.width,canvas.height,s,clock,moving?'preview':'still');lastDraw=now;dirty=false;if(showContrast&&now-lastContrast>350){updateContrast();lastContrast=now;}}}
function updateContrast(){const layer=$('#contrast-layer');if(!showContrast){layer.hidden=true;return;}layer.hidden=false;let html='';for(let row=0;row<3;row++)for(let col=0;col<3;col++){const x=(col+.5)/3,y=(row+.5)/3,p=ctx.getImageData(Math.min(canvas.width-1,Math.floor(x*canvas.width)),Math.min(canvas.height-1,Math.floor(y*canvas.height)),1,1).data,hex='#'+[p[0],p[1],p[2]].map(c=>c.toString(16).padStart(2,'0')).join(''),dark=contrastRatio(hex,'#25212C'),white=contrastRatio(hex,'#FFFFFF'),ink=dark>white?'#25212C':'#FFFFFF',contrast=Math.max(dark,white);html+=`<span class="contrast-sample" style="left:${x*100}%;top:${y*100}%;color:${ink}"><b>Aa</b><small>${contrast.toFixed(1)}:1 · ${contrast>=7?'AAA':contrast>=4.5?'AA':'Large text'}</small></span>`;}layer.innerHTML=html;}

document.addEventListener('click',event=>{
 const el=(event.target as Element).closest<HTMLElement>('button,a');if(!el||el.closest('#studio-dialog'))return;
 if(el.dataset.arrangementColours!==undefined){const palettes=store.state.type==='glow'?GLOW_PALETTES:store.state.type==='forms'?FORM_PALETTES:LINE_PALETTES,palette=palettes[Number(el.dataset.arrangementColours)];if(palette){store.update({colors:[...palette.colors],divisions:equalDivisions(palette.colors.length),points:[]});inspector.selectedPreset=-1;refreshAll();}return;}
 if(el.dataset.view){setView(el.dataset.view);return;}if(el.dataset.panel){setPanel(el.dataset.panel);return;}if(el.dataset.family){inspector.family=el.dataset.family;renderInspector();return;}if(el.dataset.type){changeType(el.dataset.type);return;}if(el.dataset.preset!==undefined){changePreset(Number(el.dataset.preset));return;}if(el.dataset.colour!==undefined){selectedColour=Number(el.dataset.colour);updateBalance();dialogs.colour(selectedColour);return;}if(el.dataset.removeColour!==undefined){removeColour(Number(el.dataset.removeColour));return;}
 if(el.dataset.selectText){inspector.selectedText=el.dataset.selectText;renderInspector();updateLayers();return;}if(el.dataset.textAlign){const t=selectedText();if(t){store.update(s=>{s.texts.find(layer=>layer.id===t.id)!.align=el.dataset.textAlign as TextLayer['align'];});renderInspector();}return;}
 if(el.dataset.paletteFilter){paletteFilter=el.dataset.paletteFilter;document.querySelectorAll<HTMLElement>('[data-palette-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.paletteFilter===paletteFilter);b.setAttribute('aria-pressed',String(b.dataset.paletteFilter===paletteFilter));});renderPalette();return;}if(el.dataset.copyHex){void copyText(el.dataset.copyHex,'Hex value copied.');return;}if(el.dataset.useColour){addColour(el.dataset.useColour);setView('studio');return;}
 if(el.dataset.openSaved){openSaved(el.dataset.openSaved);return;}if(el.dataset.deleteSaved){removeSaved(el.dataset.deleteSaved);return;}if(el.dataset.renameSaved){const id=el.dataset.renameSaved,item=saved.find(s=>s.id===id);if(item)dialogs.rename(item.name,name=>{try{writeSaved(saved.map(s=>s.id===id?{...s,name,state:{...s.state,name}}:s));}catch{toast('The design could not be renamed.');}});return;}
 switch(el.dataset.action??el.id){
  case'more-presets':inspector.expandedPresets=!inspector.expandedPresets;renderInspector();break;
  case'shuffle-points':store.update({points:store.state.colors.map(()=>[.1+Math.random()*.8,.1+Math.random()*.8])});renderInspector();break;
  case'reset-points':store.update({points:[]});renderInspector();break;
  case'reset-field':store.update({params:defaultParams(store.state.type),speed:typeById(store.state.type).speed??(typeById(store.state.type).animated?30:0)});renderInspector();break;
  case'add-colour':case'add-color':addColour();break;
  case'add-text':{const t=createText();store.update(s=>{s.texts.push(t);});inspector.selectedText=t.id;renderInspector();updateLayers();break;}
  case'duplicate-text':{const t=selectedText();if(t&&store.state.texts.length<12){const copy={...t,id:uid(),x:Math.min(90,t.x+4),y:Math.min(90,t.y+6)};store.update(s=>{s.texts.push(copy);});inspector.selectedText=copy.id;renderInspector();updateLayers();}break;}
  case'remove-text':{const t=selectedText();if(t){store.update({texts:store.state.texts.filter(text=>text.id!==t.id)});inspector.selectedText=store.state.texts[0]?.id??null;renderInspector();}break;}
  case'upload-image':$<HTMLInputElement>('#image-upload').click();break;case'remove-image':store.update({image:null});renderInspector();break;case'image-colours':void extractImageColours();break;case'import-design':$<HTMLInputElement>('#design-upload').click();break;case'back-to-studio':setView('studio');break;
  case'undo':undo();break;case'redo':redo();break;case'randomize':randomize();break;case'play-pause':togglePlayback();break;case'save':dialogs.save();break;case'share':void share();break;case'preview':void dialogs.preview();break;case'export':void dialogs.export();break;
  case'toggle-tags':showTags=!showTags;el.setAttribute('aria-label',showTags?'Hide colour tags':'Show colour tags');el.setAttribute('aria-pressed',String(showTags));updatePoints();updateTags();break;
  case'contrast':showContrast=!showContrast;el.setAttribute('aria-pressed',String(showContrast));updateContrast();break;case'set-frame':dialogs.frame();break;case'fullscreen':void fullscreen();break;case'shortcuts':dialogs.shortcuts();break;
 }
});
document.addEventListener('input',event=>{const el=event.target as HTMLInputElement;if(el.closest('#studio-dialog'))return;if(el.id==='palette-search'){paletteQuery=el.value;renderPalette();return;}
 const control=el.dataset.control;if(control){const value=Number(el.value),[target,key]=control.split(':');if(!Number.isFinite(value))return;const output=el.closest('.range-field')?.querySelector('output');if(output){const suffix=(output.textContent??'').replace(/^[-\d.]+/,'');output.textContent=String(Math.round(value*100)/100)+suffix;}el.closest<HTMLElement>('.range-control')?.style.setProperty('--fill',`${(value-Number(el.min))/(Number(el.max)-Number(el.min))*100}%`);
  if(target==='param')store.update(s=>{s.params[key]=value;},control);else if(target==='text'){const t=selectedText();if(t)store.update(s=>{Object.assign(s.texts.find(x=>x.id===t.id)!,{[key]:value});},control);}else if(target==='image')store.update(s=>{if(s.image)Object.assign(s.image,{[key]:value});},control);else if(['speed','soften','grain'].includes(target)){if(target==='speed'){paused=false;if(value>0)lastSpeed=value;}store.update({[target]:value},control);}inspector.selectedPreset=-1;return;
 }
 if(el.dataset.textControl){const t=selectedText();if(!t)return;const key=el.dataset.textControl,value=key==='weight'?Number(el.value):el.value;store.update(s=>{Object.assign(s.texts.find(x=>x.id===t.id)!,{[key]:value});},'text:'+key);if(key==='color'){const hex=el.parentElement?.querySelector('.hex-value');if(hex)hex.textContent=el.value.toUpperCase();}}
});
document.addEventListener('change',event=>{const el=event.target as HTMLInputElement|HTMLSelectElement;if(el.closest('#studio-dialog'))return;if(el.dataset.choice){store.update(s=>{s.params[el.dataset.choice!]=el.value;if(s.type==='pixel'&&el.dataset.choice==='style')Object.assign(s.params,el.value==='Orbs'?{cover:4,rings:100,weave:45}:{cover:50,rings:12,weave:20});});inspector.selectedPreset=-1;if(store.state.type==='pixel'&&el.dataset.choice==='style')renderInspector();}if(el.dataset.imageChoice)store.update(s=>{if(s.image)Object.assign(s.image,{[el.dataset.imageChoice!]:el.value});});if(el.id==='palette-sort'){paletteSort=el.value;renderPalette();}if(el.id==='image-upload'){const file=(el as HTMLInputElement).files?.[0];if(file)void uploadImage(file);}if(el.id==='design-upload'){const file=(el as HTMLInputElement).files?.[0];if(file)void importDesign(file);}});

interface Drag {kind:'point'|'text'|'image'|'balance';id:string;pointer:number;startX:number;startY:number;originX:number;originY:number;rect:DOMRect}
let drag:Drag|null=null;
document.addEventListener('pointerdown',event=>{const el=(event.target as Element).closest<HTMLElement>('[data-point],[data-drag-text],[data-drag-image],[data-balance]');if(!el||event.button!==0)return;let kind:Drag['kind']='point',id='',originX=0,originY=0;const s=store.state;if(el.dataset.point!==undefined){id=el.dataset.point;const p=(controlPoints(s))[Number(id)];originX=p[0]*100;originY=p[1]*100;}else if(el.dataset.dragText){kind='text';id=el.dataset.dragText;const t=s.texts.find(t=>t.id===id)!;originX=t.x;originY=t.y;inspector.selectedText=id;if(inspector.panel!=='text')setPanel('text');else renderInspector();}else if(el.dataset.dragImage){kind='image';originX=s.image!.x;originY=s.image!.y;if(inspector.panel!=='image')setPanel('image');}else{kind='balance';id=el.dataset.balance!;originX=s.divisions[Number(id)]*100;}drag={kind,id,pointer:event.pointerId,startX:event.clientX,startY:event.clientY,originX,originY,rect:(kind==='balance'?$('#balance-track'):frame).getBoundingClientRect()};document.body.classList.add('is-dragging');frame.setPointerCapture(event.pointerId);event.preventDefault();});
window.addEventListener('pointermove',event=>{if(!drag||drag.pointer!==event.pointerId)return;const d=drag,x=clamp(d.originX+(event.clientX-d.startX)/d.rect.width*100,0,100),y=clamp(d.originY+(event.clientY-d.startY)/d.rect.height*100,0,100);if(d.kind==='point')store.update(s=>{if(!s.points.length)s.points=controlPoints(s);s.points[Number(d.id)]=[x/100,y/100];},'drag-point');if(d.kind==='text')store.update(s=>{const t=s.texts.find(t=>t.id===d.id);if(t){t.x=x;t.y=y;}},'drag-text');if(d.kind==='image')store.update(s=>{if(s.image){s.image.x=x;s.image.y=y;}},'drag-image');if(d.kind==='balance'){const index=Number(d.id);store.update(s=>{s.divisions[index]=clamp(x/100,(s.divisions[index-1]??0)+.01,(s.divisions[index+1]??1)-.01);},'drag-balance');updateBalance();}inspector.selectedPreset=-1;});
function endDrag(){if(!drag)return;const kind=drag.kind;drag=null;document.body.classList.remove('is-dragging');if(kind==='text'||kind==='image'||kind==='point')renderInspector();}window.addEventListener('pointerup',endDrag);window.addEventListener('pointercancel',endDrag);window.addEventListener('blur',endDrag);
function moveFocused(el:HTMLElement,key:string,shift:boolean){const step=shift?5:1,direction=key==='ArrowLeft'||key==='ArrowUp'?-step:step;if(el.dataset.balance!==undefined){const index=Number(el.dataset.balance);store.update(s=>{s.divisions[index]=clamp(s.divisions[index]+direction/100,(s.divisions[index-1]??0)+.01,(s.divisions[index+1]??1)-.01);},'keyboard-balance');updateBalance();document.querySelector<HTMLElement>(`[data-balance="${index}"]`)?.focus();return true;}if(el.dataset.point!==undefined){const index=Number(el.dataset.point),axis=key==='ArrowLeft'||key==='ArrowRight'?0:1;store.update(s=>{if(!s.points.length)s.points=controlPoints(s);s.points[index][axis]=clamp(s.points[index][axis]+direction/100,0,1);},'keyboard-point');document.querySelector<HTMLElement>(`[data-point="${index}"]`)?.focus();return true;}if(el.dataset.dragText){const id=el.dataset.dragText,axis=key==='ArrowLeft'||key==='ArrowRight'?'x':'y';store.update(s=>{const t=s.texts.find(t=>t.id===id)!;t[axis]=clamp(t[axis]+direction,0,100);},'keyboard-text');document.querySelector<HTMLElement>(`[data-drag-text="${id}"]`)?.focus();return true;}if(el.dataset.dragImage&&store.state.image){const axis=key==='ArrowLeft'||key==='ArrowRight'?'x':'y';store.update(s=>{s.image![axis]=clamp(s.image![axis]+direction,0,100);},'keyboard-image');$<HTMLElement>('[data-drag-image]').focus();return true;}return false;}
document.addEventListener('keydown',event=>{const target=event.target as HTMLElement;if(dialogs.isOpen())return;if(event.key==='Escape'&&stage.classList.contains('fallback-fullscreen')){stage.classList.remove('fallback-fullscreen');resizeCanvas();return;}if(event.key.startsWith('Arrow')&&moveFocused(target,event.key,event.shiftKey)){event.preventDefault();return;}if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)&&target.matches('[data-view],[data-panel],[data-family]')){const siblings=Array.from(target.parentElement!.querySelectorAll<HTMLButtonElement>('button')),i=siblings.indexOf(target as HTMLButtonElement),next=event.key==='Home'?siblings[0]:event.key==='End'?siblings.at(-1)!:siblings[(i+(event.key==='ArrowRight'?1:-1)+siblings.length)%siblings.length];event.preventDefault();next.click();next.focus();return;}if(target.matches('input,textarea,select,[contenteditable="true"]'))return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?redo():undo();return;}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();dialogs.save();return;}if(event.ctrlKey||event.metaKey||event.altKey)return;const key=event.key.toLowerCase();if(key==='?'){event.preventDefault();dialogs.shortcuts();return;}if(view!=='studio')return;if(key===' '&&target.tagName!=='BUTTON'){event.preventDefault();togglePlayback();}if(key==='r'){event.preventDefault();randomize();}if(key==='s'){event.preventDefault();dialogs.save();}if(key==='e'){event.preventDefault();void dialogs.export();}if(key==='p'){event.preventDefault();void dialogs.preview();}if(key==='f'){event.preventDefault();void fullscreen();}});
stage.addEventListener('dragover',event=>{if(event.dataTransfer?.types.includes('Files')){event.preventDefault();stage.classList.add('drag-over');}});stage.addEventListener('dragleave',()=>stage.classList.remove('drag-over'));stage.addEventListener('drop',event=>{event.preventDefault();stage.classList.remove('drag-over');const file=event.dataTransfer?.files[0];if(file)void uploadImage(file);});inspectorContent.addEventListener('dragover',event=>{if(inspector.panel==='image'&&event.dataTransfer?.types.includes('Files'))event.preventDefault();});inspectorContent.addEventListener('drop',event=>{if(inspector.panel==='image'){event.preventDefault();const file=event.dataTransfer?.files[0];if(file)void uploadImage(file);}});document.addEventListener('paste',event=>{if(view!=='studio'||(event.target as HTMLElement).matches('input,textarea'))return;const image=Array.from(event.clipboardData?.files??[]).find(f=>f.type.startsWith('image/'));if(image){event.preventDefault();void uploadImage(image);}});
document.addEventListener('fullscreenchange',()=>{resizeCanvas();$('#fullscreen').setAttribute('aria-label',document.fullscreenElement?'Exit fullscreen':'Open fullscreen');});window.addEventListener('pagehide',()=>{cancelAnimationFrame(animationFrame);observer.disconnect();clearTimeout(draftTimer);try{localStorage.setItem(DRAFT_KEY,JSON.stringify(snapshot()));}catch{}});window.addEventListener('pageshow',event=>{if(event.persisted){observer.observe(stage);animationFrame=requestAnimationFrame(animate);}});
refreshAll();renderCounts();animationFrame=requestAnimationFrame(animate);if(startupMessage)toast(startupMessage);

type ToolContext={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown},options?:{signal:AbortSignal})=>void|Promise<void>};
const modelContext=(document as Document&{modelContext?:ToolContext}).modelContext;
if(modelContext?.registerTool){const lifecycle=new AbortController();const tools=[
 {name:'read_pigment_design',title:'Read Pigment design',description:'Read the active design, available gradient types, and saved-design count. Does not modify the design.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({design:{...snapshot(),image:store.state.image?{name:store.state.image.name}:null},types:TYPES.map(t=>({id:t.id,name:t.name,parameters:t.parameters,choices:t.choices})),savedCount:saved.length})},
 {name:'configure_pigment_design',title:'Configure Pigment design',description:'Update the visible gradient type, hex colours, numeric parameters, speed, or name in one action. Does not save or export.',inputSchema:{type:'object',properties:{type:{type:'string',enum:TYPES.map(t=>t.id)},colors:{type:'array',items:{type:'string',pattern:'^#[0-9a-fA-F]{6}$'},minItems:2,maxItems:MAX_COLOURS},params:{type:'object'},speed:{type:'number',minimum:0,maximum:100},name:{type:'string',maxLength:100}},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object')throw new Error('An object is required.');const args=input as Partial<StudioState>;if(args.type&&!TYPES.some(t=>t.id===args.type))throw new Error('Unknown gradient type.');const next={...snapshot(),...args,params:{...defaultParams(args.type??store.state.type),...(args.type===undefined?store.state.params:{}),...args.params}};if(args.colors){next.divisions=equalDivisions(args.colors.length);next.points=[];}const validated=normalizeState(next);store.replace(validated);clock=validated.time;inspector.family=POPULAR.includes(validated.type)?'Popular':typeById(validated.type).family;setView('studio');refreshAll();return{type:store.state.type,colors:store.state.colors,speed:store.state.speed};}},
 {name:'save_pigment_design',title:'Save Pigment design',description:'Save the current design in this browser’s Saved collection with the supplied name.',inputSchema:{type:'object',properties:{name:{type:'string',minLength:1,maxLength:100}},required:['name'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const name=(input as {name?:unknown})?.name;if(typeof name!=='string'||!name.trim()||name.length>100)throw new Error('A name of 1 to 100 characters is required.');const count=saved.length;await saveDesign(name.trim());if(saved.length===count)throw new Error('The design could not be saved. Browser storage may be full.');return{name:name.trim(),savedCount:saved.length};}},
 ];for(const tool of tools){try{void Promise.resolve(modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
