import { FRAME_OPTIONS, COLOURS, colourName, type StudioState } from './model';
import { renderComposition } from './renderer';
import { modal, icon, titleCase } from './ui';
import { escapeHtml as esc, downloadBlob, fileName, toBlob, svgFor, cssFor, videoFor, videoMime } from './export';

export interface DialogHost {
 state:()=>StudioState;
 update:(change:Partial<StudioState>,group?:string)=>void;
 refresh:()=>void;
 toast:(message:string)=>void;
 copy:(text:string,message?:string)=>Promise<void>;
 save:(name:string)=>Promise<void>;
 aspect:()=>number;
}
export function setupDialogs(host:DialogHost){
 const dialog=document.querySelector<HTMLDialogElement>('#studio-dialog')!,content=document.querySelector<HTMLElement>('#dialog-content')!;
 let mode='',colourIndex=0,controller:AbortController|null=null,formSubmit:((name:string)=>void)|null=null,previewImage='',formatVersion=0;
 const $=<T extends Element=HTMLElement>(selector:string)=>content.querySelector<T>(selector)!;
 function close(){controller?.abort();controller=null;dialog.close();}
 function open(kind:string,html:string,wide=false){controller?.abort();controller=null;formatVersion++;mode=kind;content.innerHTML=html;dialog.classList.toggle('wide-dialog',wide);dialog.classList.toggle('preview-dialog',kind==='preview');if(!dialog.open)dialog.showModal();}
 function error(message:string){const el=content.querySelector<HTMLElement>('#dialog-status');if(el){el.textContent=message;el.hidden=false;}else host.toast(message);}
 function namePrompt(title:string,name:string,label:string,submit:(name:string)=>void){formSubmit=submit;open('name',modal(title,`<form id="name-form"><label class="form-field"><span>Design name</span><input id="design-name" class="text-input" maxlength="100" required value="${esc(name)}" autocomplete="off"/></label><p id="dialog-status" class="error-message" hidden></p><div class="dialog-footer"><button type="button" class="outlined-button" data-dialog="close">Cancel</button><button type="submit" class="filled-button">${label}</button></div></form>`));requestAnimationFrame(()=>$<HTMLInputElement>('#design-name').select());}
 function colour(index:number){colourIndex=index;const color=host.state().colors[index];open('colour',modal('A little colour change.',`<div class="colour-picker-main" style="--picked:${color}"><input type="color" id="colour-picker" aria-label="Choose colour" value="${color}"/><span id="picker-name">${titleCase(colourName(color))}</span></div><label class="form-field hex-field"><span>Hex value</span><input id="colour-hex" class="text-input" value="${color}" pattern="#[a-fA-F0-9]{6}" maxlength="7" spellcheck="false"/><button class="icon-button" data-dialog="copy-colour" aria-label="Copy colour">${icon('copy',18)}</button></label><p class="dialog-subtitle">A few favourites</p><div class="picker-swatches">${COLOURS.filter((_,i)=>i%3===0).slice(0,32).map(c=>`<button data-picked="${c.hex}" style="background:${c.hex}" title="${esc(c.name)}" aria-label="Use ${esc(c.name)}"></button>`).join('')}</div>`,`<button class="filled-button" data-dialog="done-colour">Done ${icon('check',18)}</button>`));}
 function applyColour(color:string){if(!/^#[a-f\d]{6}$/i.test(color))return false;const colors=[...host.state().colors];colors[colourIndex]=color.toUpperCase();host.update({colors},'colour:'+colourIndex);$<HTMLInputElement>('#colour-picker').value=color;$<HTMLInputElement>('#colour-hex').value=color.toUpperCase();$('#picker-name').textContent=titleCase(colourName(color));$('.colour-picker-main').setAttribute('style',`--picked:${color}`);return true;}
 function frame(){const selected=host.state().frame;open('frame',modal('Give it a frame.',`<p class="dialog-description">Choose an aspect ratio. Your export will match the canvas.</p><div class="frame-options">${FRAME_OPTIONS.map(f=>`<button class="frame-option ${f.id===selected?'selected':''}" data-frame-id="${f.id}" aria-pressed="${f.id===selected}"><span class="frame-mini" style="aspect-ratio:${f.ratio||1.6}"></span><span>${f.name}</span>${f.id===selected?icon('check',18):''}</button>`).join('')}</div>`));}
 function shortcuts(){open('shortcuts',modal('A few useful shortcuts.',`<div class="shortcut-list">${[['Surprise me','R'],['Save design','S'],['Export','E'],['Preview','P'],['Fullscreen','F'],['Play / pause','Space'],['Undo','Ctrl / ⌘ Z'],['Redo','Ctrl / ⌘ Shift Z'],['Close panel','Esc'],['Keyboard shortcuts','?']].map(([name,key])=>`<div><span>${name}</span><kbd>${key}</kbd></div>`).join('')}</div><p class="dialog-description">Drag colour points, colour balance handles, text, and images. Focus a point or handle and use the arrow keys for precise adjustments.</p>`));}
 async function preview(){open('preview',modal('In the real world.',`<div class="preview-context segmented" role="group" aria-label="Preview context">${['Poster','Website','Phone','Card','Album'].map((c,i)=>`<button data-preview-context="${c}" class="${i===0?'selected':''}" aria-pressed="${i===0}">${c}</button>`).join('')}</div><div id="context-preview" class="context-preview"><p>Preparing your preview…</p></div>`),true);try{const canvas=await renderComposition(host.state(),960,Math.round(960/host.aspect()));if(mode!=='preview')return;previewImage=canvas.toDataURL('image/jpeg',.9);showContext('Poster');}catch(e){error((e as Error).message);}}
 function showContext(context:string){const image=`<img src="${previewImage}" alt="Your gradient in a ${context.toLowerCase()} preview"/>`;let html='';if(context==='Poster')html=`<div class="context-poster">${image}</div>`;if(context==='Phone')html=`<div class="context-phone">${image}<div class="phone-island"></div><div class="phone-time">9:41<small>Tuesday, September 15</small></div><div class="phone-bottom"></div></div>`;if(context==='Website')html=`<div class="context-website"><div class="browser-chrome"><i></i><i></i><i></i><span>your-space.design</span></div><div class="website-gradient">${image}</div><div class="website-caption"><span>A space of your own.</span><i>Explore ${icon('arrow',15)}</i></div></div>`;if(context==='Card')html=`<div class="context-card">${image}<span class="card-label">A small<br/>impression.</span><span class="card-contact">hello@your.studio</span></div>`;if(context==='Album')html=`<div class="context-album"><div class="vinyl-disc"></div><div class="album-cover">${image}<span>CHROMATIC<small>Volume 01</small></span></div></div>`;$('#context-preview').innerHTML=html;content.querySelectorAll<HTMLButtonElement>('[data-preview-context]').forEach(b=>{b.classList.toggle('selected',b.dataset.previewContext===context);b.setAttribute('aria-pressed',String(b.dataset.previewContext===context));});}
 async function exportDialog(){
  const state=host.state(),width=1920,height=Math.round(width/host.aspect());open('export',modal('Take your colour with you.',`<div class="export-preview" id="export-preview"></div><div class="export-form"><label class="form-field"><span>Format</span><select id="export-format"><option value="png">PNG · Image</option><option value="svg">SVG · Design file</option><option value="mp4" ${!videoMime('mp4')?'disabled':''}>MP4 · Video${!videoMime('mp4')?' (unavailable in this browser)':''}</option><option value="webm" ${!videoMime('webm')?'disabled':''}>WebM · Video</option><option value="css">CSS · Background</option><option value="json">JSON · Editable design</option></select></label><div id="export-size" class="export-size"><label class="form-field"><span>Width</span><input id="export-width" type="number" min="64" max="4096" value="${width}"/></label><span>×</span><label class="form-field"><span>Height</span><input id="export-height" type="number" min="64" max="4096" value="${height}"/></label><span class="field-caption">px</span></div><label class="checkbox-field" id="ratio-row"><input type="checkbox" id="export-lock" checked/>Keep aspect ratio</label><div id="video-options" hidden><label class="form-field"><span>Duration</span><select id="video-duration"><option value="3">3 seconds</option><option value="5" selected>5 seconds</option><option value="10">10 seconds</option><option value="15">15 seconds</option></select></label><p class="control-hint">Keep this tab open while recording. The video starts at the current frame and follows the selected speed.</p></div><label id="text-export-row" class="checkbox-field"><input type="checkbox" id="export-text" checked/>Include text and image</label><p id="export-note" class="control-hint">A full-resolution snapshot of your design.</p><textarea id="export-code" class="text-input code-output" rows="6" readonly aria-label="Exported code" hidden></textarea><p id="dialog-status" class="error-message" hidden></p><div id="export-progress" hidden><progress max="100" value="0"></progress><span>Preparing…</span></div></div>`,`<button class="outlined-button" id="export-copy" data-dialog="copy-code" hidden>${icon('copy',17)}Copy code</button><button class="filled-button" id="export-download" data-dialog="download">${icon('download',18)}Download PNG</button>`));
  try{const preview=await renderComposition(state,440,Math.round(440/host.aspect()));if(mode==='export')$('#export-preview').append(Object.assign(new Image(),{src:preview.toDataURL('image/jpeg',.85),alt:'Export preview'}));}catch(e){error((e as Error).message);}
 }
 async function updateExportFormat(){
  const version=++formatVersion,format=$<HTMLSelectElement>('#export-format').value,video=format==='mp4'||format==='webm';$('#video-options').hidden=!video;$('#export-code').hidden=format!=='css';$('#export-copy').hidden=format!=='css'&&format!=='svg';$('#export-size').hidden=format==='json'||format==='css';$('#ratio-row').hidden=format==='json'||format==='css';$('#text-export-row').hidden=format==='css'||format==='json';$('#export-download').innerHTML=icon('download',18)+`Download ${format.toUpperCase()}`;
  $('#dialog-status').hidden=true;$('#export-progress').hidden=true;$<HTMLButtonElement>('#export-download').disabled=false;$<HTMLButtonElement>('#export-copy').disabled=false;
  if(video){$<HTMLInputElement>('#export-width').value='1280';$<HTMLInputElement>('#export-height').value=String(Math.round(1280/host.aspect()));}
  const notes:Record<string,string>={png:'A full-resolution snapshot of your design.',svg:'Linear and radial fields without grain or softening stay vector. Other fields embed the rendered image; text stays editable. Install the selected typeface when editing the SVG.',mp4:'MP4 video, recorded entirely in your browser.',webm:'WebM video, recorded entirely in your browser.',css:cssFor(host.state(),host.aspect())?'Copy this CSS into your stylesheet. Text and images are separate layers.':'The gradient, including grain and softening, is exported as a still PNG background embedded in CSS.',json:'Keeps your colours, parameters, text, and image. Import it from Saved to continue editing.'};$('#export-note').textContent=notes[format];
  if(format==='css'){
   const code=cssFor(host.state(),host.aspect());$<HTMLTextAreaElement>('#export-code').value=code??'';
   if(!code){
    $<HTMLButtonElement>('#export-download').disabled=true;$<HTMLButtonElement>('#export-copy').disabled=true;
    try{const canvas=await renderComposition({...host.state(),texts:[],image:null},960,Math.round(960/host.aspect()));if(mode==='export'&&version===formatVersion){$<HTMLTextAreaElement>('#export-code').value=`background-image: url("${canvas.toDataURL('image/png')}");\nbackground-size: cover;\nbackground-position: center;`;$<HTMLButtonElement>('#export-download').disabled=false;$<HTMLButtonElement>('#export-copy').disabled=false;}}
    catch(e){if(mode==='export'&&version===formatVersion)error((e as Error).message);}
   }
  }
 }
 function dimensions(){const width=Math.round(Number($<HTMLInputElement>('#export-width').value)),height=Math.round(Number($<HTMLInputElement>('#export-height').value));if(!Number.isFinite(width)||!Number.isFinite(height)||width<64||height<64||width>4096||height>4096||width*height>12000000)throw new Error('Choose dimensions between 64 and 4096 px, up to 12 million pixels in total.');return {width,height};}
 async function download(copy=false){
  const format=$<HTMLSelectElement>('#export-format').value;let state=host.state();if(!$<HTMLInputElement>('#export-text').checked)state={...state,texts:[],image:null};const stem=fileName(state.name),button=$<HTMLButtonElement>('#export-download');button.disabled=true;
  try{const {width,height}=format==='json'||format==='css'?{width:0,height:0}:dimensions();if(format==='json'){downloadBlob(new Blob([JSON.stringify(host.state(),null,2)],{type:'application/json'}),stem+'.pigment.json');}
   else if(format==='png'){const canvas=await renderComposition(state,width,height);downloadBlob(await toBlob(canvas),stem+'.png');}
   else if(format==='svg'){const svg=await svgFor(state,width,height);if(copy)await host.copy(svg,'SVG copied.');else downloadBlob(new Blob([svg],{type:'image/svg+xml'}),stem+'.svg');}
   else if(format==='css'){const css=$<HTMLTextAreaElement>('#export-code').value;if(!css)throw new Error('Your CSS is still being prepared. Please try again.');if(copy)await host.copy(css,'CSS copied.');else downloadBlob(new Blob([`.pigment-background {\n  ${css.replaceAll('\n','\n  ')}\n}\n`],{type:'text/css'}),stem+'.css');}
   else if(format==='mp4'||format==='webm'){
    controller=new AbortController();$('#export-progress').hidden=false;content.querySelectorAll<HTMLInputElement|HTMLSelectElement>('input,select').forEach(e=>e.disabled=true);
    const blob=await videoFor(state,width,height,Number($<HTMLSelectElement>('#video-duration').value),format,p=>{$<HTMLProgressElement>('#export-progress progress').value=p;$('#export-progress span').textContent=`Recording ${p}%`;},controller.signal);downloadBlob(blob,stem+'.'+format);controller=null;
   }
   host.toast(copy?'Code copied.':'Your export is ready.');
  }catch(e){if((e as Error).name!=='AbortError')error((e as Error).message);}finally{if(mode==='export'){button.disabled=false;content.querySelectorAll<HTMLInputElement|HTMLSelectElement>('input,select').forEach(e=>e.disabled=false);}}
 }
 content.addEventListener('click',event=>{
  const el=(event.target as Element).closest<HTMLElement>('button');if(!el)return;
  if(el.dataset.action==='close-dialog'||el.dataset.dialog==='close'){close();return;}
  if(el.dataset.picked){applyColour(el.dataset.picked);return;}
  if(el.dataset.frameId){host.update({frame:el.dataset.frameId});host.refresh();close();return;}
  if(el.dataset.previewContext){showContext(el.dataset.previewContext);return;}
  switch(el.dataset.dialog){case'done-colour':host.refresh();close();break;case'copy-colour':void host.copy(host.state().colors[colourIndex],'Colour copied.');break;case'download':void download();break;case'copy-code':void download(true);break;}
 });
 content.addEventListener('input',event=>{const el=event.target as HTMLInputElement;
  if(el.id==='colour-picker'){applyColour(el.value);return;}if(el.id==='colour-hex'){const valid=applyColour(el.value.startsWith('#')?el.value:'#'+el.value);el.setAttribute('aria-invalid',String(!valid));return;}
  if((el.id==='export-width'||el.id==='export-height')&&$<HTMLInputElement>('#export-lock').checked){if(el.id==='export-width')$<HTMLInputElement>('#export-height').value=String(Math.round(Number(el.value)/host.aspect()));else $<HTMLInputElement>('#export-width').value=String(Math.round(Number(el.value)*host.aspect()));}
 });
 content.addEventListener('change',event=>{if((event.target as HTMLElement).id==='export-format')void updateExportFormat();});
 content.addEventListener('submit',event=>{event.preventDefault();if((event.target as HTMLElement).id==='name-form'){const value=$<HTMLInputElement>('#design-name').value.trim();if(value){close();formSubmit?.(value);}}});
 dialog.addEventListener('cancel',()=>{controller?.abort();controller=null;});
 dialog.addEventListener('close',()=>{if(mode==='colour')host.refresh();mode='';formatVersion++;});
 dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)close();}});
 return {colour,frame,shortcuts,preview,export:exportDialog,close,isOpen:()=>dialog.open,
  save:()=>namePrompt('Keep this colour.',host.state().name,'Save design',name=>void host.save(name)),
  rename:(name:string,callback:(name:string)=>void)=>namePrompt('A new name.',name,'Rename',callback),
  message:(title:string,text:string)=>open('message',modal(title,`<p class="dialog-description">${esc(text)}</p>`,`<button class="filled-button" data-dialog="close">Done</button>`)),
  copyFallback:(text:string)=>open('copy',modal('Copy your design.',`<p class="dialog-description">Select and copy the text below.</p><textarea class="text-input code-output" rows="6" readonly aria-label="Text to copy">${esc(text)}</textarea>`)),
 };
}
