import { MAX_COLOURS, TYPES, FAMILIES, POPULAR, PRESETS, FONTS, COLOURS, typeById, colourName, colourFamily, hue, luminance, inkFor, contrastRatio, type StudioState, type Parameter } from './model';
import { escapeHtml as esc } from './export';
import type { SavedDesign } from './store';
import { presetSwatch } from './preset-swatch.ts';
import { GLOW_PALETTES } from './glow.ts';
import { LINE_PALETTES } from './lines.ts';
import { FORM_PALETTES, FORM_SHAPES } from './forms.ts';
export const paths:Record<string,string>={
 plus:'M12 5v14M5 12h14',close:'m6 6 12 12M6 18 18 6',check:'m5 12 4 4L19 6',arrow:'M5 12h14m-6-6 6 6-6 6',
 trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7',copy:'M8 8h12v13H8zM4 16H2V2h12v2',
 bookmark:'M6 4h12v17l-6-4-6 4z',image:'M3 4h18v16H3zm0 12 6-6 5 5 3-3 4 4M16 8h.01',
 text:'M4 5h16M12 5v15M8 20h8',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',
 upload:'M12 16V4m-5 5 5-5 5 5M4 16v5h16v-5',pause:'M8 5v14M16 5v14',play:'m9 5 11 7-11 7z',
 eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7-10-7-10-7Zm13 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',
 search:'M15 15l6 6M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0Z',shuffle:'M3 7h3c5 0 7 10 12 10h3m-4-4 4 4-4 4M3 17h3c1 0 2-.5 3-1.5M14 8.5C15 7.5 16 7 18 7h3m-4-4 4 4-4 4',
 sparkle:'m12 2 2.6 7.4L22 12l-7.4 2.6L12 22l-2.6-7.4L2 12l7.4-2.6z',palette:'M12 3a9 9 0 1 0 0 18h1a2 2 0 0 0 1-3.7 1.5 1.5 0 0 1 1-2.8h2a4 4 0 0 0 4-4A8.5 8.5 0 0 0 12 3ZM7 10h.01M10 6.5h.01M15 7h.01M17.5 10.5h.01',
};
export const icon=(name:string,size=20)=>`<svg class="icon" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]??paths.sparkle}"/></svg>`;
export const titleCase=(s:string)=>s.toLowerCase().replace(/(^|[\s-])\S/g,c=>c.toUpperCase());
export function rangeHTML(key:string,label:string,value:number,min=0,max=100,unit='%',step=1){return `<label class="range-field"><span>${esc(label)}<output>${Math.round(value*100)/100}${unit}</output></span><span class="range-control" style="--fill:${(value-min)/(max-min)*100}%"><input type="range" data-control="${key}" aria-label="${esc(label)}" min="${min}" max="${max}" step="${step}" value="${value}"/></span></label>`;}
const paramHTML=(p:Parameter,state:StudioState)=>rangeHTML(`param:${p.key}`,p.label,Number(state.params[p.key]??p.value),p.min,p.max,p.unit,p.step??1);
const section=(title:string,body:string,extra='')=>`<section class="control-section"><div class="section-heading"><h2>${title}</h2>${extra}</div>${body}</section>`;
export function coloursHTML(state:StudioState){return state.colors.map((c,i)=>`<div class="colour-row"><button class="colour-edit" data-colour="${i}" aria-label="Edit ${esc(colourName(c))}" style="background:${c}"></button><button class="colour-name-button" data-colour="${i}"><strong>${titleCase(colourName(c))}</strong><span>${c} <span class="contrast-grade">${contrastRatio(c,'#25212C')>=7?'AAA':contrastRatio(c,'#25212C')>=4.5?'AA':''}</span></span></button><button class="icon-button tiny" data-remove-colour="${i}" aria-label="Remove colour ${i+1}" ${state.colors.length<=2?'disabled':''}>${icon('close',16)}</button></div>`).join('');}
export interface InspectorOptions { panel:string; family:string; selectedText:string|null; expandedPresets:boolean; selectedPreset:number }
export function inspectorHTML(state:StudioState,options:InspectorOptions):string{
 if(options.panel==='text')return textInspector(state,options.selectedText);
 if(options.panel==='image')return imageInspector(state);
 const kind=typeById(state.type),types=options.family==='Popular'?TYPES.filter(t=>POPULAR.includes(t.id)).sort((a,b)=>POPULAR.indexOf(a.id)-POPULAR.indexOf(b.id)):TYPES.filter(t=>t.family===options.family);
 const allPresets=PRESETS.map((p,i)=>({p,i})).filter(({p})=>p.type===state.type),presets=options.expandedPresets?allPresets:allPresets.slice(0,12);
 const arranged=['glow','lines','forms'].includes(state.type);
 const presetButtons=presets.map(({p,i})=>{
  const active=arranged&&state.type!=='forms'?p.params.arrangement===state.params.arrangement:i===options.selectedPreset;
  return arranged?`<button class="arrangement-preset ${active?'active':''}" data-preset="${i}" aria-pressed="${active}"><canvas data-preset-thumb="${i}" width="120" height="84" aria-hidden="true"></canvas><span>${esc(p.name)}</span></button>`:`<button class="preset ${active?'active':''}" data-preset="${i}" aria-pressed="${active}" title="${esc(p.name)}"><span class="preset-disc">${presetSwatch(p.colors)}${active?'<span class="preset-check">'+icon('check',12)+'</span>':''}</span><span>${esc(p.name)}</span></button>`;
 }).join('');
 const colourPalettes=state.type==='glow'?GLOW_PALETTES:state.type==='forms'?FORM_PALETTES:LINE_PALETTES;
 const retint=arranged?section('Colour palettes',`<div class="preset-grid">${colourPalettes.map((p,i)=>{const active=p.colors.join(',').toLowerCase()===state.colors.join(',').toLowerCase();return `<button class="preset ${active?'active':''}" data-arrangement-colours="${i}" aria-pressed="${active}"><span class="preset-disc">${presetSwatch(p.colors)}${active?'<span class="preset-check">'+icon('check',12)+'</span>':''}</span><span>${esc(p.name)}</span></button>`;}).join('')}</div>`,`<span class="field-caption">retint your arrangement</span>`):'';
 const parameters=state.type==='pixel'?kind.parameters.filter(p=>p.key==='scale'||(state.params.style==='Glass'?p.key==='cover':state.params.style==='Orbs'?true:p.key!=='cover')).map(p=>p.key==='cover'?{...p,label:state.params.style==='Orbs'?'Gap':'Fill',max:state.params.style==='Orbs'?30:100}:p.key==='rings'?{...p,label:state.params.style==='Orbs'?'Roundness':'Steps',min:state.params.style==='Orbs'?0:2,max:state.params.style==='Orbs'?100:16}:p.key==='weave'?{...p,label:state.params.style==='Orbs'?'Glow':'Weave'}:p):kind.parameters;
 return section('Gradient type',`<div class="family-tabs" role="tablist" aria-label="Type family">${FAMILIES.map(f=>`<button role="tab" aria-selected="${options.family===f}" data-family="${f}" class="${options.family===f?'active':''}">${f}</button>`).join('')}</div><div class="type-grid">${types.map(t=>`<button class="type-option ${state.type===t.id?'active':''}" data-type="${t.id}" aria-pressed="${state.type===t.id}"><span>${t.name}</span></button>`).join('')}</div>`,`<span class="field-caption">${kind.name}</span>`)
 +section('Presets',`<div class="${arranged?'arrangement-grid':'preset-grid'}">${presetButtons}</div>${allPresets.length>12?`<button class="quiet-button more-presets" data-action="more-presets">${options.expandedPresets?'Show less':`All ${allPresets.length} presets`}</button>`:''}`,`<span class="field-caption">${arranged?'arrangements':`for ${kind.name.toLowerCase()}`}</span>`)
 +retint
 +((state.type==='flow'||state.type==='mesh')?section('Colour spots',`<div class="inline-buttons"><button class="small-tonal" data-action="shuffle-points">${icon('shuffle',15)} Shuffle</button><button class="quiet-button" data-action="reset-points" ${!state.points.length?'disabled':''}>Reset</button></div><p class="control-hint">Drag the rings on the canvas to place each colour.</p>`):'')
 +((kind.parameters.length||kind.choices?.length||kind.animated)?section(state.type==='flow'?'Field':state.type==='silk'?'Fabric':state.type==='sky'?'Weather':state.type==='aurora'?'Lights':'Shape',`<div class="parameter-list">${(kind.choices??[]).filter(c=>!arranged||c.key!=='arrangement').map(c=>`<label class="select-field"><span>${c.label}</span><select data-choice="${c.key}" aria-label="${c.label}">${c.options.map(v=>`<option value="${esc(v)}" ${state.params[c.key]===v?'selected':''}>${esc(state.type==='forms'&&c.key==='shape'?FORM_SHAPES.find(s=>s.id===v)?.name??v:v)}</option>`).join('')}</select></label>`).join('')}${parameters.map(p=>paramHTML(p,state)).join('')}${kind.animated?rangeHTML('speed','Speed',state.speed):''}</div>`,`<button class="quiet-button" data-action="reset-field">Reset</button>`):state.type==='waves'?section('Wave layers',`<p class="control-hint">Each colour creates one softly curved layer. Drag the colour bands below the canvas to set their depth.</p>`):'')
 +section('Colours',`<div id="color-list">${coloursHTML(state)}</div><button class="tonal-button full-width" data-action="add-colour" ${state.colors.length>=MAX_COLOURS?'disabled':''}>${icon('plus',17)}Add colour</button>`,`<span class="field-caption">${state.colors.length} / ${MAX_COLOURS}</span>`)
 +section('Finish',`<div class="parameter-list">${rangeHTML('soften','Soften',state.soften,0,80,'px')}${rangeHTML('grain','Noise',state.grain)}</div>`);
}
function textInspector(state:StudioState,selectedId:string|null){
 const t=state.texts.find(t=>t.id===selectedId)??state.texts[0];
 let html=section('Text layers',`<div class="layer-list">${state.texts.map(layer=>`<button class="layer-option ${t?.id===layer.id?'active':''}" data-select-text="${layer.id}">${icon('text',17)}<span>${esc(layer.content.split('\n')[0]||'Empty text')}</span></button>`).join('')}</div><button class="tonal-button full-width" data-action="add-text" ${state.texts.length>=12?'disabled':''}>${icon('plus',17)}Add text</button>`);
 if(!t)return html+'<div class="panel-empty">'+icon('text',40)+'<p>A few words can change everything.</p><span>Add a text layer to your gradient.</span></div>';
 html+=section('Words',`<label class="sr-only" for="text-content">Text content</label><textarea id="text-content" data-text-control="content" class="text-input" rows="3" maxlength="1000">${esc(t.content)}</textarea><div class="inline-buttons layer-actions"><button class="quiet-button" data-action="duplicate-text">${icon('copy',15)}Duplicate</button><button class="quiet-button danger" data-action="remove-text">${icon('trash',15)}Remove</button></div>`);
 html+=section('Typography',`<div class="parameter-list"><label class="select-field"><span>Typeface</span><select data-text-control="font" aria-label="Typeface">${FONTS.map(f=>`<option value="${f.id}" ${f.id===t.font?'selected':''}>${f.name}</option>`).join('')}</select></label><label class="select-field"><span>Weight</span><select data-text-control="weight" aria-label="Font weight">${[400,500,600,700].map(w=>`<option value="${w}" ${t.weight===w?'selected':''}>${({400:'Regular',500:'Medium',600:'Semibold',700:'Bold'} as Record<number,string>)[w]}</option>`).join('')}</select></label>${rangeHTML('text:size','Size',t.size,1,40,'% of width',.1)}${rangeHTML('text:tracking','Letter spacing',t.tracking,-10,30,'%')}<div class="alignment-group" role="group" aria-label="Text alignment">${['left','center','right'].map(a=>`<button data-text-align="${a}" aria-pressed="${t.align===a}" class="${t.align===a?'active':''}">${titleCase(a)}</button>`).join('')}</div><label class="colour-input-field"><span>Colour</span><input type="color" value="${t.color}" data-text-control="color" aria-label="Text colour"/><span class="hex-value">${t.color}</span></label></div>`);
 return html+section('Position & finish',`<div class="parameter-list">${rangeHTML('text:x','Position X',t.x,0,100)}${rangeHTML('text:y','Position Y',t.y,0,100)}${rangeHTML('text:rotation','Rotation',t.rotation,-180,180,'°')}${rangeHTML('text:opacity','Opacity',t.opacity)}${rangeHTML('text:shadow','Shadow',t.shadow)}</div><p class="control-hint">You can also drag text directly on the canvas.</p>`);
}
function imageInspector(state:StudioState){
 const i=state.image;let html=section('Image layer',`<input type="file" id="image-upload" accept="image/png,image/jpeg,image/webp,image/avif" hidden/><button class="upload-zone" data-action="upload-image">${icon('upload',30)}<strong>${i?'Replace image':'Drop an image here'}</strong><span>or choose a file · PNG, JPG, WebP</span></button>`);
 if(!i)return html+'<div class="panel-empty">'+icon('image',40)+'<p>Make it your own.</p><span>Add a photograph, a cutout, or a logo.</span></div>';
 html+=section('Your image',`<div class="image-summary"><img src="${i.src}" alt="Uploaded image thumbnail"/><span>${esc(i.name)}</span><button class="icon-button" data-action="remove-image" aria-label="Remove image">${icon('trash',18)}</button></div><button class="small-tonal full-width" data-action="image-colours">${icon('palette',17)}Use image colours</button>`);
 return html+section('Position',`<div class="parameter-list">${rangeHTML('image:width','Size',i.width,5,180,'%')}${rangeHTML('image:x','Position X',i.x,0,100)}${rangeHTML('image:y','Position Y',i.y,0,100)}${rangeHTML('image:rotation','Rotation',i.rotation,-180,180,'°')}</div>`)+section('Appearance',`<div class="parameter-list"><label class="select-field"><span>Blend mode</span><select data-image-choice="blend" aria-label="Image blend mode">${['normal','multiply','screen','overlay','soft-light','luminosity'].map(b=>`<option value="${b}" ${b===i.blend?'selected':''}>${titleCase(b)}</option>`).join('')}</select></label>${rangeHTML('image:opacity','Opacity',i.opacity)}${rangeHTML('image:radius','Corner radius',i.radius,0,50,'%')}${rangeHTML('image:brightness','Brightness',i.brightness,0,200,'%')}${rangeHTML('image:contrast','Contrast',i.contrast,0,200,'%')}${rangeHTML('image:blur','Blur',i.blur,0,30,'px')}</div>`);
}
export function paletteHTML(){return `<div class="collection-heading"><div><span class="eyebrow">A LIBRARY OF COLOUR</span><h1>Find your next favourite.</h1><p>Traditional Japanese colours, ready for your next blend.</p></div><span class="collection-total">${COLOURS.length}<small>colours</small></span></div><div class="palette-tools"><label class="search-field">${icon('search')}<input type="search" id="palette-search" placeholder="Search a name or hex…" aria-label="Search colours"/></label><label class="sort-field"><span class="sr-only">Sort colours</span><select id="palette-sort" aria-label="Sort colours"><option value="hue">By hue</option><option value="light">Light to dark</option><option value="dark">Dark to light</option><option value="name">By name</option></select></label></div><div class="filter-chips" role="group" aria-label="Colour family">${['All','Red','Orange','Yellow','Green','Teal','Blue','Purple','Pink','Neutral'].map(f=>`<button data-palette-filter="${f}" class="filter-chip ${f==='All'?'active':''}" aria-pressed="${f==='All'}">${f}</button>`).join('')}</div><p class="collection-hint">Choose a colour to add it to your design. Use the copy button for its hex value.</p><div id="palette-grid" class="palette-grid"></div>`;}
export function paletteGridHTML(query:string,filter:string,sort:string){
 const q=query.trim().toLowerCase();const colours=COLOURS.filter(c=>(filter==='All'||colourFamily(c.hex)===filter)&&(!q||`${c.name} ${c.hex} ${c.japanese} ${c.romaji}`.toLowerCase().includes(q))).sort((a,b)=>sort==='light'?luminance(b.hex)-luminance(a.hex):sort==='dark'?luminance(a.hex)-luminance(b.hex):sort==='name'?a.name.localeCompare(b.name):hue(a.hex)-hue(b.hex));
 return colours.length?colours.map(c=>`<article class="palette-card" style="--colour:${c.hex};--ink:${inkFor(c.hex)}"><button class="palette-use" data-use-colour="${c.hex}" aria-label="Use ${esc(c.name)} in studio"><span class="colour-japanese">${c.japanese}</span><span class="palette-card-name">${titleCase(c.name)}</span><span class="palette-card-hex">${c.hex}</span><span class="palette-add">${icon('plus',18)}</span></button><button class="palette-copy" data-copy-hex="${c.hex}" aria-label="Copy ${c.hex}">${icon('copy',16)}</button></article>`).join(''):`<div class="empty-state compact">${icon('search',40)}<h2>No colours found</h2><p>Try another name, hex value, or colour family.</p></div>`;
}
export function savedHTML(saved:SavedDesign[]){return `<div class="collection-heading"><div><span class="eyebrow">YOUR PERSONAL COLLECTION</span><h1>A little colour, kept.</h1><p>Your saved designs live in this browser, ready to pick up again.</p></div><button class="outlined-button" data-action="import-design">${icon('upload',18)}Import design</button><input type="file" id="design-upload" accept="application/json,.json" hidden/></div>${saved.length?`<div class="saved-grid">${saved.map(s=>`<article class="saved-card"><button class="saved-art" data-open-saved="${esc(s.id)}" aria-label="Open ${esc(s.name)}">${s.thumbnail?`<img src="${s.thumbnail}" alt="${esc(s.name)} gradient" loading="lazy"/>`:`<div style="background:linear-gradient(135deg,${s.state.colors.join(',')})"></div>`}<span class="saved-open">${icon('arrow',22)}</span></button><div class="saved-meta"><button class="saved-title" data-open-saved="${esc(s.id)}"><strong>${esc(s.name)}</strong><span>${typeById(s.state.type).name} · ${s.state.colors.length} colours</span></button><button class="icon-button" data-rename-saved="${esc(s.id)}" aria-label="Rename ${esc(s.name)}">${icon('text',18)}</button><button class="icon-button" data-delete-saved="${esc(s.id)}" aria-label="Remove ${esc(s.name)}">${icon('trash',18)}</button></div></article>`).join('')}</div>`:`<div class="empty-state"><span class="empty-symbol">${icon('bookmark',38)}</span><h2>Good colours are worth keeping.</h2><p>Save a blend in the studio.<br/>You’ll find it right here.</p><button class="filled-button" data-action="back-to-studio">Back to studio ${icon('arrow',18)}</button></div>`}`;}
export function modal(title:string,body:string,footer=''){return `<div class="dialog-heading"><h2>${title}</h2><button class="icon-button" data-action="close-dialog" aria-label="Close dialog">${icon('close')}</button></div>${body}${footer?`<div class="dialog-footer">${footer}</div>`:''}`;}
